#!/bin/sh
# Point-in-time recovery from physical base backup + WAL archive.
#
# Prerequisites:
#   - Base backup directory from backup-postgres-base.sh (contains base.tar.gz)
#   - WAL archive volume/dir populated by postgres archive_command
#   - Stack STOPPED (especially postgres)
#
# This script prepares files into RECOVERY_WORK_DIR. You then replace the
# postgres data volume contents and start postgres (see docs/BACKUP_RESTORE.md).
#
# Example (on the VPS, after copying artifacts):
#   BASE_DIR=./backups/base/20260101T000000Z \
#   WAL_ARCHIVE_DIR=./backups/wal_archive \
#   RECOVERY_TARGET_TIME='2026-01-01 12:00:00+00' \
#   RECOVERY_WORK_DIR=./backups/recovery_work \
#     ./infra/scripts/restore-postgres-pitr.sh

set -eu

BASE_DIR="${BASE_DIR:-}"
WAL_ARCHIVE_DIR="${WAL_ARCHIVE_DIR:-}"
RECOVERY_WORK_DIR="${RECOVERY_WORK_DIR:-./backups/recovery_work}"
RECOVERY_TARGET_TIME="${RECOVERY_TARGET_TIME:-}"

if [ -z "${BASE_DIR}" ] || [ ! -d "${BASE_DIR}" ]; then
  echo "Set BASE_DIR to a pg_basebackup output directory (with base.tar.gz)." >&2
  exit 1
fi
if [ -z "${WAL_ARCHIVE_DIR}" ] || [ ! -d "${WAL_ARCHIVE_DIR}" ]; then
  echo "Set WAL_ARCHIVE_DIR to the Postgres WAL archive directory." >&2
  exit 1
fi
if [ ! -f "${BASE_DIR}/base.tar.gz" ]; then
  echo "Missing ${BASE_DIR}/base.tar.gz" >&2
  exit 1
fi

rm -rf "${RECOVERY_WORK_DIR}"
mkdir -p "${RECOVERY_WORK_DIR}/pgdata" "${RECOVERY_WORK_DIR}/wal_archive"

echo "[pitr] extracting base backup"
tar -xzf "${BASE_DIR}/base.tar.gz" -C "${RECOVERY_WORK_DIR}/pgdata"

echo "[pitr] copying WAL archive"
cp -a "${WAL_ARCHIVE_DIR}/." "${RECOVERY_WORK_DIR}/wal_archive/"

# Tablespace tarball may exist from pg_basebackup -Ft
if [ -f "${BASE_DIR}/pg_wal.tar.gz" ]; then
  echo "[pitr] extracting bundled pg_wal.tar.gz"
  mkdir -p "${RECOVERY_WORK_DIR}/pgdata/pg_wal"
  tar -xzf "${BASE_DIR}/pg_wal.tar.gz" -C "${RECOVERY_WORK_DIR}/pgdata/pg_wal"
fi

RESTORE_COMMAND="cp /wal_archive/%f %p"

{
  echo "# Generated by restore-postgres-pitr.sh"
  echo "restore_command = '${RESTORE_COMMAND}'"
  if [ -n "${RECOVERY_TARGET_TIME}" ]; then
    echo "recovery_target_time = '${RECOVERY_TARGET_TIME}'"
    echo "recovery_target_action = 'promote'"
  else
    # Recover as far as WAL allows, then open for writes.
    echo "recovery_target_action = 'promote'"
  fi
} > "${RECOVERY_WORK_DIR}/pgdata/postgresql.auto.conf"

touch "${RECOVERY_WORK_DIR}/pgdata/recovery.signal"

echo "[pitr] prepared recovery tree at ${RECOVERY_WORK_DIR}"
echo
echo "Manual cut-over (Docker Compose):"
echo "  1) docker compose stop api worker web postgres"
echo "  2) Replace postgres_data volume contents with ${RECOVERY_WORK_DIR}/pgdata"
echo "     (see docs/BACKUP_RESTORE.md for a safe volume copy recipe)."
echo "  3) Ensure WAL archive is mounted at /wal_archive inside the postgres container"
echo "     (compose already mounts postgres_wal_archive → /wal_archive)."
echo "  4) Sync host WAL copy into the wal_archive volume if needed."
echo "  5) docker compose start postgres  # watch logs until recovery finishes / promotes"
echo "  6) pnpm --filter @finenumbers/db prisma migrate deploy"
echo "  7) docker compose start worker api web"
echo "  8) Verify /health/ready + a known wallet balance"
